= Изменения в составе триацилглицеролов в созревающих семенах облепихи (Hippophaë rhamnoides)

**Российский журнал физиологии растений, Том 50, № 3, 2003, стр. 381-389. Переведено из журнала "Физиология растений", Том 50, № 3, 2003, стр. 428-436. Оригинальный русский текст © 2003, Верещагин, Цыдендамбаев.**

**А.Г. Верещагин и В.Д. Цыдендамбаев**
Институт физиологии растений Российской академии наук, ул. Ботаническая, 35, Москва, 127276, Россия;
факс: 7 (095) 977-8018; e-mail: ifr@ippras.ru
Получено 16 января 2002 г.

== Аннотация

Для определения качественного и количественного состава позиционных типов, групп и позиционных видов триацилглицеролов (ТАГ), а также фактора селективности включения ненасыщенных жирных кислот, октадеценовой, линолевой и линоленовой, в sn-2-позицию ТАГ, были использованы семена облепихи (Hippophaë rhamnoides L.) на 29-й, 53-й, 80-й и 107-й день после опыления. Гидролиз проводился с помощью липазы. До 80-го дня после опыления преобладало образование триненасыщенных ТАГ, в состав которых входили остатки линоленовой и линолевой кислот. После 80-го дня абсолютное содержание этих основных компонентов общих ТАГ заметно снижалось, и увеличение общего содержания ТАГ в основном происходило за счет увеличения уровня тех видов ТАГ, которые включали насыщенные жирные кислоты, пальмитиновую и стеариновую (мононенасыщенные-двуненасыщенные и диненасыщенные-мононенасыщенные), а также за счет уровня sn-2-октадеценоильных видов, принадлежащих к триненасыщенным и пальмито-диненасыщенным типам ТАГ. На каждой стадии созревания количественная динамика отдельных видов ТАГ определялась содержанием видов жирных кислот, доступных для образования ТАГ, и фактором селективности этих видов. Обнаруженное здесь снижение содержания определенной группы триненасыщенных ТАГ, по-видимому, обусловлено их метаболизмом во время созревания семян.

**Ключевые слова:** Hippophaë rhamnoides, фактор селективности, позиционный тип состава, позиционный вид состава, sn-2 ацилирование, стадии созревания, кинетическая константа относительной скорости биосинтеза, мононасыщенные-диненасыщенные триацилглицеролы, триненасыщенные триацилглицеролы.

== ВВЕДЕНИЕ

В отличие от других основных запасных веществ семян, количественный и, часто, качественный состав триацилглицеролов (ТАГ) подвергается значительным изменениям в процессе созревания плодов. Поэтому для решения одной из важнейших проблем современной липидологии, а именно производства растительных масел с заданным составом и увеличения их содержания в семенах, необходимо, прежде всего, выяснить характер этих изменений как основу для механизма биосинтеза запасных ТАГ [1]. Тем не менее, в большинстве случаев ТАГ созревающих семян изучались только на уровне их состава по жирным кислотам, а изменения в видовом составе самих ТАГ остаются малоизученными [2].
В качестве материала для определения этих изменений особый интерес представляют плоды облепихи (Hippophaë rhamnoides), поскольку они характеризуются двумя различными типами накопления масла, характерными для мезокарпия и семян соответственно. Во многих отношениях эти плоды отличаются от запасающих органов других растений в отношении закономерностей биосинтеза и метаболизма ТАГ [3].
Ранее изменения в количественном составе видов ТАГ в процессе созревания плодов облепихи определялись только в мезокарпии [3], а исследования ТАГ семян включали определение их состава и структуры в зрелых плодах [4], изменения их состава по жирным кислотам во время роста [5] и характера этого состава в отдельных географических формах (климатотипах) Hippophaë rhamnoides [6, 7]. Было показано, что эти ТАГ во многих отношениях сильно отличаются от ТАГ мезокарпия [4-7].
Эти различия включают более высокую скорость биосинтеза ТАГ семян и более короткий период их накопления [5]. Кроме того, эти ТАГ характеризуются преобладанием остатков C18 ЖК и в этом отношении отличаются от ТАГ мезокарпия, где преобладают остатки C16 ЖК [4-7]. Наконец, различные климатотипы облепихи близки друг к другу по составу ЖК ТАГ семян, но могут значительно отличаться по составу ТАГ мезокарпия и механизму их биосинтеза [7]. Все эти различия между семенами и мезокарпием могут быть вызваны генетическими факторами, поскольку во всех случаях зародыш семени включает равные доли генов обоих родителей, тогда как мезокарпий облепихи является соматическим органом только с материнским генотипом [5].
Таким образом, лучшее понимание непосредственных причин наблюдаемых различий и получение более подробной картины биосинтеза ТАГ в плодах облепихи представляло бы значительный интерес. С этой целью было необходимо определить изменения в основных показателях количественного видового состава ТАГ не только в мезокарпии [3], но и в созревающих семенах этих плодов. Целью данной работы было решение этой проблемы. Изменения этих показателей в развивающихся эмбрионах облепихи и других видов растений с маслоносным мезокарпием ранее не изучались [5].

== МАТЕРИАЛЫ И МЕТОДЫ

Как и в наших предыдущих исследованиях, использовались растения облепихи (Hippophaë rhamnoides L., сорт Дар Катуни). Качественный и количественный состав ТАГ в образцах семян определяли методом гидролиза с помощью липазы [3, 5-7]. Мы количественно определяли позиционные типы ТАГ, которые характеризуются определенным составом насыщенных (S) и ненасыщенных (U) ЖК, а также средним или экстремальным положением S и U в молекуле ТАГ ([SSU], [USU], [SUS], [SUU] и [UUU], мас. % от общих ТАГ). Во-вторых, мы оценили концентрации позиционных видов ТАГ (мас. % от общих ТАГ), характеризующихся определенным составом отдельных ЖК, а именно пальмитиновой (P), стеариновой (St), гексадеценовой (H), октадеценовой (O), линолевой (L) и линоленовой (Le), и, кроме того, sn-2- или rac-1,3-положением этих остатков ЖК в молекуле ТАГ [3].
Все эти показатели состава определяли на i-й день после опыления (ДПО), где i = 29, 53, 80 и 107. Также оценивали состав ТАГ, образованных на каждой из последовательных стадий созревания семян, а именно на стадии 29-53 ДПО (стадия 1), 53-80 ДПО (стадия 2) и 80-107 ДПО (стадия 3) [3].
Изменения в накоплении ТАГ выражали в виде изменений их концентрации (мас. % от общих ТАГ) и абсолютного содержания (P, нмоль этерифицированных ЖК на семя) на i-й ДПО. В этом случае значения P наносились на логарифмическую шкалу, поскольку на последовательных стадиях развития семян разница между этими значениями могла достигать нескольких порядков [5]. Изменения этих значений на 3-й стадии созревания (ΔP, %) рассчитывали по формуле:
ΔP = [(P3 - P2)P2-1] × 100%,
где P2 и P3 — это значения P на 2-й и 3-й стадиях соответственно.
Среднюю интенсивность образования типов и видов ТАГ в процессе развития семян выражали кинетической константой относительной скорости (k, 1/день) этого процесса [3, 5]. Константу k рассчитывали по уравнению:
k = (k1,1 + k1,2 + ... + k1,n)(n – 2)–1,
(1)
где
k1 = {ln[(P – P0)P–1] – ln[(P – P1)P–1]}T1–1,
(2)
это константа скорости на i-й ДПО (см. выше); n - это количество стадий созревания, изученных здесь, т.е. количество образцов семян различного возраста; P, P0 и Pi (нмоль этерифицированных ЖК на семя) - это значения абсолютного содержания ТАГ в зрелых семенах (107-й ДПО), семенах зеленых плодов (29-й ДПО) и семенах на i-й ДПО соответственно; T1 - это количество дней между начальным (29-й ДПО) и i-м ДПО [8]. Ранее уравнение (2) в основном использовалось в химии для характеристики кинетики автокаталитической мономолекулярной реакции, но в то же время оно использовалось для количественного описания процессов роста и накопления запасных веществ в растениях [9, 10].
Сродство U-видов ЖК (за исключением гексадеценовой) к sn-2-позиции ТАГ характеризовали фактором селективности включения этих видов в среднюю позицию. Этот фактор рассчитывали по формуле ([U]1, 2, 3 × [Uj]2)/([Uj]1, 2, 3 × [U]2), где U - это сумма ненасыщенных ЖК (O + L + Le); Uj - это j-я ненасыщенная ЖК (O, L или Le); [U] и [Uj] - это содержание общих ненасыщенных ЖК и j-й ЖК в мас. %; 1, 2 и 3 обозначают общие ТАГ; 2 обозначает sn-2-позицию ТАГ [3, 4, 7].
Значения в таблицах и на рисунках представляют средние значения из экспериментов, выполненных в трех повторностях; во всех случаях относительные стандартные отклонения не превышали 7% от среднего значения.

== РЕЗУЛЬТАТЫ

=== Формирование позиционных типов ТАГ

Семена облепихи содержат не более 7% от общих ТАГ всего плода, но по концентрации ТАГ (% от сырой массы) они значительно превосходят мезокарпий (13-22 против 2-4% соответственно) [5]. Как показано в таблице 1, позиционные типы ТАГ, содержащие U в sn-2-положении (ТАГ класса 2), всегда преобладали в общих ТАГ семян, а типы, включающие S в этом положении (ТАГ класса 1), обычно не составляли более 1-2% от общих ТАГ.
Наибольшая скорость образования общих ТАГ семян была достигнута на 68-71-й ДПО [8], и по значению константы скорости биосинтеза (k × 103 ~ 230 1/день) они были близки к общим ЖК, для которых значение k было установлено ранее [5]. В то же время таблица 1 демонстрирует, что различные типы ТАГ характеризовались разной скоростью биосинтеза, и значения k были ниже для ТАГ класса 1, чем для ТАГ класса 2. Эта разница в скорости биосинтеза также подтверждалась большей крутизной кривых 5-7 для ТАГ класса 2 по сравнению с кривыми 1-3 для ТАГ класса 1 на рисунке 1 [8]. Интересно, что во время образования масла в мезокарпии облепихи, значения k для ТАГ класса 1 превышали значения k для ТАГ класса II в 1,14 раза [3].
После 80-го ДПО интенсивность общего накопления UUU значительно снижалась, и основной вклад в биосинтез ТАГ на конечной стадии (стадия 3) созревания семян вносили типы ТАГ, которые содержали остатки S и составляли 76,2% от общих ТАГ, образованных на этой стадии (таблица 1). Такой типоспецифический характер накопления ТАГ на стадии 3 был вызван увеличенным образованием S в этот период (см. таблицу 3 в [5]).

=== Формирование основных позиционных видов ТАГ типа SUU

Как показано в таблицах 2 и 3, изменения в содержании позиционных видов ТАГ представлены только для основных типов ТАГ, то есть SUU и UUU, которые вместе составляли более 97% от общих ТАГ в зрелых семенах. Кроме того, во внимание принимались только основные позиционные виды, то есть те виды, уровень которых, по крайней мере, на некоторой стадии развития, был равен или превышал 0,3% от общих ТАГ; общее содержание этих видов варьировалось от 77 до 95% (таблицы 2, 3). Таким образом, все данные, представленные ниже, относятся только к основным видам ТАГ позиционных типов SUU и UUU.
Что касается ТАГ типа SUU, то их концентрация на 107-й ДПО составляла 20,6% (таблица 2). Как показано на рисунке 2, накопление всех этих видов было очень активным до 80-го ДПО. Однако их биосинтез продолжался до 107-го ДПО, и в течение стадии 3 развития их абсолютное содержание увеличилось примерно на 25% (таблица 2).
Что касается характера количественных изменений в содержании отдельных позиционных видов ТАГ, то общие SUU можно было разделить на несколько групп, и каждая из них характеризовалась определенным составом и структурой ЖК (таблица 2, рисунок 2). Группа 1 состояла из позиционных видов ТАГ, которые включали, наряду с P, только остатки L и Le. Эта группа отличалась от других групп SUU наибольшей концентрацией, наименьшей скоростью биосинтеза (k), и наименее интенсивным образованием на стадии созревания 3 (ΔP = 7,3%).
Следующей по абсолютному содержанию после группы 1 была группа 2, которая отличалась от первой наличием остатков O и более высокой скоростью образования (таблица 2, рисунок 2). Значительная часть общих ТАГ группы 2 образовалась на стадии 3. По мере этого происходило увеличение абсолютного уровня sn-2-O-позиционных видов, которые составляли подгруппу 2а, более чем в полтора раза, в то время как уровень sn-2-L + sn-2-Le-видов (подгруппа 2b) увеличился всего на 20%.
Наконец, позиционные виды SUU, в состав которых вместо P входил St (группа 3), характеризовались самой низкой концентрацией, и по скорости образования (k × 103 ~ 238 1/день) группа 3 была аналогична группе 2 (k × 103 ~ 239 1/день; таблица 2, рисунок 2). На стадии 3 абсолютное содержание ТАГ группы 3 почти удвоилось (ΔP = 91%). Это резкое увеличение может быть вызвано резким усилением образования St во время стадии 3. Аналогично, довольно слабое увеличение содержания группы 1 (см. выше) можно объяснить снижением скорости синтеза L и Le в этот же период (см. таблицу 3 в [5]). Другими словами, в этих случаях характер количественных изменений в содержании видов SUU на стадии созревания 3 определялся различиями в количестве тех видов ЖК, которые на этой стадии были доступны для образования определенного вида SUU [3].
В то же время на стадии 3 содержание видов ТАГ группы 2, которые включали остатки O, увеличивалось в основном за счет ТАГ подгруппы 2a (см. выше), в то время как вклад ТАГ подгруппы 2b, содержащих O только в их rac-1,3-положениях, в значение ΔP был гораздо менее важным (таблица 2, рисунок 2). Можно предположить, что этот характер изменений был вызван усилением включения O в sn-2-положение ТАГ на стадии созревания 3. Поэтому мы определили фактор селективности включения O, L и Le на различных ДПО (рисунок 3). Видно, что на стадии 3 включение O в среднее положение ТАГ действительно увеличивалось.

=== Формирование основных позиционных видов ТАГ типа UUU

В процессе созревания концентрация этих видов в общих ТАГ варьировалась от 58 до 72% (таблица 3). Сумма основных видов UUU несколько превышала основные виды SUU по скорости их образования (k × 103 ~ 241 1/день).
Как и SUU, позиционные виды UUU можно было разделить на несколько групп (группы 4-7, таблица 3). Видно, что ТАГ группы 4 отличались от других ТАГ семян самой низкой скоростью образования (k × 103 ~ 202 1/день) и наличием остатка H в каждом из их видов. До 53-го ДПО группа 4 была одним из основных компонентов UUU, но к концу созревания ее концентрация снизилась до менее чем 1%. Тем не менее, даже на стадии 3 абсолютное содержание ТАГ этой группы выросло на 10,8% (таблица 3, рисунок 4).
Группа 5 отличалась от группы 4 несколько более высокой скоростью образования (таблица 3, рисунок 4). Кроме того, ТАГ группы 5 (кроме OLL, см. ниже) включали только остатки Le и L, и по своей концентрации эта группа превышала другие группы ТАГ (таблицы 2, 3). Фактически, к 80-му ДПО, когда образование Le и L достигло своего максимума [5], группа 5 составляла почти половину общих ТАГ семян (таблица 3).
Однако наиболее важной особенностью ТАГ группы 5, которая отличала их не только от других UUU, но и от всех других ТАГ семян, было то, что их биосинтез полностью прекратился к 80-му ДПО, то есть задолго до конца созревания. Более того, на стадии 3 абсолютное содержание общих ТАГ группы 5 снизилось (ΔP ~ 7%). Явление снижения уровня высоконенасыщенной группы ТАГ в созревающих семенах пока не объяснено.
Все, кроме одной, характеристики отдельных видов ТАГ группы 5, описанные выше, не относятся к виду OLL. Последний был включен в группу 5 только потому, что на стадии 3 его содержание также не увеличивалось (таблица 3).
Позиционные виды UUU, находящиеся за пределами групп 4 и 5, характеризовались общей структурной особенностью, то есть наличием остатков O (таблица 3); единственным исключением из этого правила был OLL (см. выше), а также LeLeLe, обсужденный далее. Тем не менее, эти позиционные виды ТАГ были разделены здесь на две отдельные группы (6 и 7) в соответствии с наличием и отсутствием O в их sn-2-позиции соответственно. Более того, эти группы существенно отличались друг от друга по скорости их образования на различных стадиях созревания; максимумы этой скорости наблюдались на стадиях 3 и 2 соответственно (таблица 3, рисунок 4).
Sn-2-O-позиционные виды, составляющие группу 6, вырабатывались в течение всего периода созревания.

Однако их синтез был особенно активным после 80-го ДПО (ΔP = 36,4%), когда образовалась более трети общих ТАГ этой группы (таблица 3, рисунок 4). Видно, что по характеру своего накопления группа 6 была похожа на подгруппу 2a (см. ниже), и по скорости ее биосинтеза (k × 103 ~ 240 1/день), она заметно превышала группы 4 и 5 и, в этом отношении, была близка к группам 1-3 (таблица 2).
В свою очередь, ТАГ группы 7 характеризовались наличием только Le или L в их sn-2-положении, а остатки O встречались только в их rac-1,3-положениях (таблица 3). Как упоминалось выше, вид LeLeLe, не содержащий O, является исключением для других видов этой группы. Более того, LeLeLe отличался от всех них тем, что на стадии 3 увеличение его абсолютного содержания было очень низким, всего 2%. В этом отношении LeLeLe был несколько похож на некоторые виды ТАГ группы 5, например LeLLe, содержание которого в конце созревания также было практически постоянным (ΔP = -0,03%, таблица 3).
Наконец, группа 7 отличалась от других ТАГ семян самой высокой скоростью биосинтеза (k × 103 ~ 247 1/день). Пик образования группы 7 совпадал со стадией 2, как и в случае с группой 5 (см. выше). Между тем, на стадии роста 3 абсолютное содержание группы 7 увеличилось лишь менее чем на 9% (таблица 3, рисунок 4).
Этот эффект, по-видимому, был вызван снижением сродства Le к sn-2-положению ТАГ (рисунок 3) и прекращением биосинтеза L на этой стадии (см. ниже).

=== Изменения в позиционно-видовом составе триацилглицеролов на отдельных стадиях созревания

Видно, что виды UUU преобладали среди основных видов ТАГ семян, за ними следовали виды SUU. Все эти виды, за исключением, возможно, OLL и LeLeLe, можно было четко разделить по крайней мере на семь групп ТАГ, различающихся по структуре и составу ЖК, концентрации в течение периода роста, скорости биосинтеза и характеру количественных изменений на стадии созревания 3 (ΔP).
Сравнение этих данных с количественными изменениями в составе ЖК ТАГ семян облепихи, обнаруженными нами ранее (см. таблицу 3 и рисунки 1-3 в [5]), позволяет сделать вывод о том, что на стадиях 1 и 2 преобладало образование видов UUU, после чего их содержание в целом оставалось почти неизменным. Более того, на стадии 1 этот процесс сопровождался интенсивным накоплением видов ТАГ, содержащих остатки P и H, из-за селективного образования соответствующих видов ЖК [3]. На стадии 2 это сопровождалось усиленным накоплением видов, богатых остатками Le и L и принадлежащих к группам 1, 5 и 7; это, опять же, было вызвано преимущественным образованием Le и L в течение этого периода [3].
Особый интерес представляет характер изменений в значениях ΔP, то есть в уровнях видов ТАГ на стадии созревания 3. Из-за общего ослабления синтеза ТАГ на этой стадии (см. рисунки 1, 2, 4) влияние обоих регуляторных факторов этого процесса, то есть концентрации определенных видов ЖК и степени их сродства к sn-2-OH глицерильной группе, на изменения в составе ТАГ можно было проследить более легко. Таким образом, видно, что возобновление образования S и, особенно, St привело к резкому увеличению содержания SSU, USU и SUS, а также ТАГ групп 2 и 3. В то же время снижение концентрации Le и ее сродства к sn-2-OH, наряду с прекращением образования L (см. ниже), были ответственны за очень умеренное увеличение (ΔP) количества групп 1 и 7. Между тем это снижение не могло объяснить снижение абсолютного содержания ТАГ группы 5, которые преобладают в общих ТАГ, и пока нет удовлетворительного объяснения этому факту.
Прекращение синтеза L после 80-го ДПО (см. таблицу 3 в [5]) привело к значительным сдвигам в изменениях L-содержащих (L-ТАГ) видов, и эти сдвиги стали более выраженными по мере увеличения количества L-остатков в L-ТАГ. Наблюдаемые сдвиги включали умеренное увеличение и значительное снижение абсолютного содержания L-ТАГ в группах 1 и 5 соответственно. Фактор селективности L не влиял на образование видов L-ТАГ, поскольку в течение всего развития семян этот фактор был почти постоянным (рисунок 3). Напротив, сродство O к sn-2-положению ТАГ неуклонно возрастало, что привело к увеличению абсолютного содержания подгруппы 2a и группы 6 на стадии созревания 3 (ΔP = 54,5 и 36,4% соответственно).
Как упоминалось выше, существует прямая связь между концентрациями отдельных классов ТАГ и их значениями k (таблица 1). В то же время не было такой связи для групп 1-7, рассмотренных выше. Так, группы 4 и 5 были похожи по значениям k × 10-3 (202 и ~208 1/день), но сильно отличались друг от друга по содержанию в ТАГ зрелых семян (0,7 и 40,2% соответственно). Непосредственные причины различий между отдельными группами ТАГ в их значениях k в настоящее время не ясны.

== ОБСУЖДЕНИЕ

Представленные здесь данные показывают, что в созревающих семенах облепихи, как и в ее мезокарпии [11], состав позиционных видов ТАГ может изменяться под действием ряда факторов. Было показано, что одним из этих факторов является изменение в составе видов ЖК, доступных на определенной стадии созревания для биосинтеза ТАГ [12]. Как правило, созревание семян сопровождается увеличением и уменьшением концентраций U и S соответственно [13-15]. В целом облепиха схожа с другими изученными до сих пор видами растений по характеру изменений этих показателей в семенах (см. таблицу 2 в [5]). В то же время она отличалась от этих видов повышенным содержанием Le (33-35%) в ТАГ; изменения в видовом составе ТАГ, которые в зрелых семенах содержат более 10% остатков Le, ранее не определялись. Более того, здесь впервые наблюдалось резкое усиление биосинтеза StLeLe, StLLe и StLL, вызванное повышением уровня St на конечной стадии созревания. Нам удалось обнаружить это явление только благодаря тому, что, во-первых, позиционный видовой состав ТАГ был впервые выражен не только в процентах, как это было во всех предыдущих работах, кроме [16], но и в виде значений абсолютного содержания, нмоль на семя (рисунок 2), и, во-вторых, был установлен состав ТАГ, образованных на каждой отдельной стадии созревания (таблица 2). Наконец, снижение уровня L-ТАГ из-за прекращения образования L на конечной стадии (таблица 3) также было вызвано этим фактором. Ранее было показано, что созревание семян крестоцветных сопровождалось образованием новых видов ТАГ, в состав которых входили остатки эруковой и эйкозеновой кислот; это было вызвано тем, что производство этих видов ЖК началось только после начала интенсивного биосинтеза ТАГ [2]. Однако никаких качественных сдвигов в составе ТАГ в созревающих семенах облепихи не наблюдалось.
Другим фактором изменений в их составе был сдвиг в позиционной специфичности ферментов биосинтеза ТАГ. Этот сдвиг выражался в изменениях сродства отдельных видов ЖК к определенным положениям глицерильного остатка [11]. В процессе созревания семян облепихи значение этого сродства влияло на изменения уровня видов ТАГ в основном в группах 2, 6 и 7. Ранее изменения сродства ненасыщенных ЖК к sn-2-положению ТАГ наблюдались при созревании семян подсолнечника; в этих ТАГ олеат на 38-й ДПО превосходил линолеат в этом отношении [17]. В то же время во всех других случаях, включая семена облепихи (рисунок 3), олеат занимал гораздо более низкое место по сравнению с линолеатом в этом отношении. Между тем, состав ЖК sn-2-положения ТАГ сои и кукурузы оставался постоянным на протяжении всего созревания, и сдвиги в их позиционно-видовом составе были вызваны только изменениями в составе ЖК, которые были включены в sn-1- и sn-3-положения ТАГ [12, 18].
Снижение абсолютного содержания одной из групп ТАГ, то есть группы 5, демонстрирует, что метаболизм ТАГ, отложенных в липидных телах клетки, можно рассматривать как еще один фактор изменения состава ТАГ в созревающих семенах облепихи. Свидетельства возможности такого метаболизма до окончания созревания можно найти и в ряде работ, опубликованных ранее.
Во-первых, до начала экспоненциальной фазы накопления масла семена подсолнечника [15, 17], кукурузы [18], сои [1, 12, 19] и сафлора [20] содержали виды ТАГ, которые по своему составу были совершенно необычными для масел этих растений. Поскольку эти виды ТАГ, которые обычно включали остатки Le и S, полностью отсутствовали в зрелых семенах, был сделан вывод о том, что они подвергаются метаболизму во время созревания [21].
Во-вторых, в винограде с 18-го по 24-й ДПО наблюдалось двукратное снижение абсолютного содержания видов ТАГ, которые включали L и O. Это снижение было вызвано потреблением некоторых видов ТАГ в дыхании, а других — в биосинтезе фенольных соединений [16]. Наконец, к концу созревания семян подсолнечника снижение концентрации UUU в общих ТАГ с 76,4% до 71,4% за счет снижения содержания OOO, OLO и OLL сопровождалось определенным увеличением уровня LLL [15]. Это снижение может быть объяснено десатурацией остатков O в ТАГ с образованием L-ТАГ [18]; чистое снижение абсолютного содержания видов rac-1,3-O ТАГ в созревающем мезокарпии облепихи с образованием соответствующих видов rac-1,3-L было объяснено аналогично [11]. В то же время снижение L- и Le-ТАГ в группе 5 во время созревания семян этого вида растений не могло быть объяснено их прямой десатурацией, поскольку это не сопровождалось каким-либо значительным увеличением содержания LeLeLe, предполагаемого продукта этой реакции (таблица 3).
Необычный механизм трансформации запасных ТАГ был обнаружен в созревающих семенах Lunaria annua. Было показано, что в ходе этого процесса ЖК C22:1 и C24:1 включались только в sn-1- и sn-3-положения ТАГ и равномерно распределялись между ними. Если биосинтез ТАГ в L. annua проходил в соответствии с классическим путем Кеннеди [11], то эти виды ЖК должны были бы обнаруживаться в sn-1-положениях промежуточных продуктов этого пути, таких как лизофосфатидные кислоты, фосфатидные кислоты и sn-1,2-диацилглицерины. Однако фактически остатки ЖК C22:1 и C24:1 отсутствовали в этих положениях. Таким образом, эти виды ЖК первоначально присутствовали только в sn-3-положении ТАГ и могли включаться в их sn-1-положение только за счет ацильного обмена между предварительно сформированными ТАГ в конце созревания [22, 23]. Поэтому возможно, что снижение абсолютного содержания ТАГ группы 5 в семенах облепихи также было вызвано переносом их остатков ацилов на другие липиды.

== БЛАГОДАРНОСТИ

Эта работа была поддержана Российским фондом фундаментальных исследований, проект № 99-04-49208.

== ЛИТЕРАТУРА

1. Wilson, R.F. and Rinne, R.W., Lipid Molecular Species Composition in Developing Soybean Cotyledons, Plant Physiol., 1978, vol. 61, pp. 830-833.
2. Norton, G. and Harris, J.F., Triacylglycerols in Oilseed Rape during Seed Development, Phytochemistry, 1983, vol. 22, pp. 2703–2707.
3. Berezhnaya, G.A., Ozerinina, O.V., Tsydendambaev, V.D., and Vereshchagin, A.G., Changes in Triacylglycerol Composition in the Mesocarp of Developing Sea Buckthorn Fruit, Fiziol. Rast. (Moscow), 1997, vol. 44, pp. 338-346 (Russ. J. Plant Physiol., Engl. Transl.).
4. Ozerinina, O.V., Berezhnaya, G.A., Eliseev, I.P., and Vereshchagin, A.G., The Composition and Structure of Triacylglycerols of Hippophaë rhamnoides Seeds, Khim. Prir. Soedin., 1987, no. 1, pp. 52–57.
5. Berezhnaya, G.A., Ozerinina, O.V., Eliseev, I.P., Tsydendambaev, V.D., and Vereshchagin, A.G., Developmental Changes in the Absolute Content and Fatty Acid Composition of