equivalent_carbon_number_composition = Композиция по эквивалентному углеродному числу
    .abbreviation = ЭУЧК
positional_equivalent_carbon_number_composition = Позиционная композиция по эквивалентному углеродному числу
    .abbreviation = ПЭУЧК
stereo_equivalent_carbon_number_composition = Стерео композиция по эквивалентному углеродному числу
    .abbreviation = СЭУЧК
mass_composition = Композиция по массе
    .abbreviation = МК
positional_mass_composition = Позиционная композиция по массе
    .abbreviation = ПМК
stereo_mass_composition = Стерео композиция по массе
    .abbreviation = СМК
type_composition = Композиция по типу
    .abbreviation = ТК
positional_type_composition = Позиционная композиция по типу
    .abbreviation = ПТК
stereo_type_composition = Стерео композиция по типу
    .abbreviation = СТК
species_composition = Композиция по виду
    .abbreviation = ВК
positional_species_composition = Позиционная композиция по виду
    .abbreviation = ПВК
stereo_species_composition = Стерео композиция по виду
    .abbreviation = СВК
