experimental = Эксперимент
factors = Факторы
identifier = Идентификатор
    .abbreviation = ИД
index = Индекс
label = Метка
theoretical = Расчеты

fatty_acid = Жирная кислота
    .abbreviation = ЖК
triacylglycerol = Триацилглицерин
    .abbreviation = ТАГ
diacylglycerol = Диацилглицерин
    .abbreviation = ДАГ
monoacylglycerol = Моноацилглицерин
    .abbreviation = МАГ
enrichment_factor = Фактор обогощения
    .abbreviation = ФО
selectivity_factor = Фактор селективности
    .abbreviation = ФС
