about = О программе
calculation = Вычисления
composition = Композиция
configuration = Конфигурация
create = Создать
edit = Редактировать
grid = Сетка
horizontal = Горизонтально
language = Язык
left_panel = Левая панель
list = Список
load = Загрузить
reset_application = Сбросить данные приложения
reset_gui = Сбросить настройки интерфейса
reset_table = Сбросить настройки таблицы
resize_table = Изменить размер столбцов таблицы
save = Сохранить
settings = Настройки
tabs = Вкладки
vertical = Вертикально