equivalent_carbon_number_composition = Equivalent carbon number composition
    .abbreviation = ECNC
positional_equivalent_carbon_number_composition = Positional equivalent carbon number composition
    .abbreviation = PECNC
stereo_equivalent_carbon_number_composition = Stereo equivalent carbon number composition
    .abbreviation = SECNC
mass_composition = Mass composition
    .abbreviation = MC
positional_mass_composition = Positional mass composition
    .abbreviation = PMC
stereo_mass_composition = Stereo mass composition
    .abbreviation = SMC
type_composition = Type composition
    .abbreviation = TC
positional_type_composition = Positional type composition
    .abbreviation = PTC
stereo_type_composition = Stereo type composition
    .abbreviation = STC
species_composition = Species composition
    .abbreviation = SC
positional_species_composition = Positional species composition
    .abbreviation = PSC
stereo_species_composition = Stereo species composition
    .abbreviation = SSC