mass_nonstereospecific_composition = Mass non-stereospecific composition
    .abbreviation = MNC
mass_stereospecific_composition = Mass stereospecific composition (agregation)
    .abbreviation = MSC
equivalent_carbon_number_nonstereospecific_composition = Equivalent carbon number non-stereospecific composition (agregation)
    .abbreviation = NNC
equivalent_carbon_number_stereospecific_composition = Equivalent carbon number stereospecific composition
    .abbreviation = NSC
species_nonstereospecific_composition = Species non-stereospecific composition (permutation)
    .abbreviation = SNC
species_positionalspecific_composition = Species positional specific composition (permutation)
    .abbreviation = SPC
species_stereospecific_composition = Species stereospecific composition
    .abbreviation = SSC
type_nonstereospecific_composition = Type non-stereospecific composition (permutation)
    .abbreviation = TNC
type_positionalspecific_composition = Type positional specific composition (permutation)
    .abbreviation = TPC
type_stereospecific_composition = Type stereospecific composition
    .abbreviation = TSC
unsaturation_nonstereospecific_composition = Unsaturation non-stereospecific composition (agregation)
    .abbreviation = UNC
unsaturation_stereospecific_composition = Unsaturation stereospecific composition
    .abbreviation = USC
