# https://byrdwell.com/Triacylglycerols/FattyAcids.htm

c4u0 =
    .abbreviation = Bu
    .common_name = Butyric acid
    .systematic_name = Butanoic acid
c5u0 =
    .abbreviation = V
    .common_name = Valeric acid
    .systematic_name = Pentanoic acid
c6u0 =
    .abbreviation = Co
    .common_name = Caproic acid
    .systematic_name = Hexanoic acid
c7u0 =
    .abbreviation = En
    .common_name = Enanthic acid
    .systematic_name = Heptanoic acid
c8u0 =
    .abbreviation = Cy
    .common_name = Caprylic acid
    .systematic_name = Octanoic acid
c9u0 =
    .common_name = Pelargonic acid
    .systematic_name = Nonanoic acid
c10u0 =
    .abbreviation = Ca
    .common_name = Capric acid
    .systematic_name = Decanoic acid
c11u0 =
    .common_name = Undecylic acid
    .systematic_name = Hendecanoic acid
c12u0 =
    .abbreviation = La
    .common_name = Lauric acid
    .systematic_name = Dodecanoic acid
c13u0 =
    .common_name = Tridecylic acid
    .systematic_name = Tridecanoic acid
c14u0 =
    .abbreviation = M
    .common_name = Myristic acid
    .systematic_name = Tetradecanoic acid
c15u0 =
    .common_name = Pentadecylic acid
    .systematic_name = Pentadecanoic acid
c16u0 =
    .abbreviation = P
    .common_name = Palmitic acid
    .systematic_name = Hexadecanoic acid
c16u1c9 =
    .abbreviation = Po
    .common_name = Palmitoleic acid
    .systematic_name = c-9-Hexadecenoic acid
c16u1t9 =
    .abbreviation = Pe
    .common_name = Palmitelaidic acid
    .systematic_name = t-9-Hexadecenoic acid
c17u0 =
    .common_name = Margaric acid
    .systematic_name = Heptadecanoic acid
c18u0 =
    .abbreviation = S
    .common_name = Stearic acid
    .systematic_name = Octadecanoic acid
c18u1c9 =
    .abbreviation = O
    .common_name = Oleic acid
    .systematic_name = c-9-Octadecenoic acid
c18u1t9 =
    .abbreviation = El
    .common_name = Elaidic acid
    .systematic_name = t-9-Octadecenoic acid
c18u2c9c12 =
    .abbreviation = L
    .common_name = Linoleic acid
    .systematic_name = c-9,12-Octadecadienoic acid
c18u3c9c12c15 =
    .abbreviation = Ln
    .common_name = a-Linolenic acid
    .systematic_name = c-9,12,15-Octadecatrienoic acid
c18u3c6c9c12 =
    .abbreviation = g-Ln
    .common_name = g-Linolenic acid, GLA
    .systematic_name = c-6,9,12-Octadecatrienoic acid
c18u3c9t11t13 =
    .abbreviation = Eo
    .common_name = a-Eleostearic acid
    .systematic_name = 9c,11t,13t-Octadecatrienoic acid
c18u3t9t11t13 =
    .common_name = b-Eleostearic acid
    .systematic_name = 9t,11t,13t-Octadecatrienoic acid
c18u3c8t10c12 =
    .abbreviation = Ja
    .common_name = Jacaric acid
    .systematic_name = 8c,10t,12c-Octadecatrienoic acid
c18u3t9t11c13 =
    .abbreviation = Ct
    .common_name = Catalpic acid
    .systematic_name = 9t,11t,13c-Octadecatrienoic acid
c18u4c6c9c12c15 =
    .abbreviation = St
    .common_name = Stearidonic acid
    .systematic_name = c-6,9,12,15-Octadecatetraenoic acid
c19u0 =
    .common_name = Nonadecylic acid
    .systematic_name = Nonadecanoic acid
c20u0 =
    .abbreviation = A
    .common_name = Arachidic acid
    .systematic_name = Eicosanoic acid
c20u1c9 =
    .abbreviation = G
    .common_name = Gadoleic acid
    .systematic_name = c-9-Eicosenoic acid
c20u1c11 =
    .abbreviation = Go
    .common_name = Gondoic acid
    .systematic_name = c-11-Eicosenoic acid
c20u2c11c14 =
    .common_name = DihomoLinoleic acid
    .systematic_name = c-11,14-Eicosadienoic acid
c20u3c11c14c17 =
    .common_name = Bis-homo-a-Linolenic acid, ETA
    .systematic_name = c-11,14,17-Eicosatrienoic acid
c20u3c8c11c14 =
    .common_name = Bis-homo-g-Linolenic acid
    .systematic_name = c-8,11,14-Eicosatrienoic acid
c20u3c5c8c11 =
    .common_name = Mead acid
    .systematic_name = c-5,8,11-Eicosatrienoic acid
c20u4c5c8c11c14 =
    .abbreviation = Ao
    .common_name = Arachidonic acid
    .systematic_name = c-5,8,11,14-Eicosatetraenoic acid
c20u4c8c11c14c17 =
    .common_name = Eicosatetraenoic acid
    .systematic_name = c-8,11,14,17-Eicosatetraenoic acid
c20u5c5c8c11c14c17 =
    .abbreviation = Ep
    .common_name = EPA
    .systematic_name = c-5,8,11,14,17-EicosaPentaenoic acid
c21u0 =
    .common_name = Heneicosylic acid
    .systematic_name = Heneicosanoic acid
c22u0 =
    .abbreviation = B
    .common_name = Behenic acid
    .systematic_name = Docosanoic acid
c22u1c13 =
    .abbreviation = E
    .common_name = Erucic acid
    .systematic_name = c-13-Docosenoic acid
c22u2c13c16 =
    .common_name = Docosadienoic acid
    .systematic_name = c-13,16-Docosadienoic acid
c22u3c5c13c16 =
    .common_name = Eranthic acid
    .systematic_name = c-5,13,16-Docosatrienoic acid
c22u4c7c10c13c16 =
    .common_name = Adrenic acid
    .systematic_name = c-7,10,13,16-Docosatetraenoic acid
c22u5c7c10c13c16c19 =
    .abbreviation = Dp
    .common_name = DPA
    .systematic_name = c-7,10,13,16,19-DocosaPentaenoic acid
c22u6c4c7c10c13c16c19 =
    .abbreviation = Dh
    .common_name = DHA
    .systematic_name = c-4,7,10,13,16,19-DocosaHexaenoic acid
c23u0 =
    .common_name = Tricosylic acid
    .systematic_name = Tricosanoic acid
c24u0 =
    .abbreviation = Lg
    .common_name = Lignoceric acid
    .systematic_name = Tetracosanoic acid
c24u1c15 =
    .abbreviation = N
    .common_name = Nervonic acid
    .systematic_name = c-15-Tetracosenoic acid
c24u2c15c18 =
    .common_name = Tetracosadienoic acid
    .systematic_name = c-15,18-Tetracosadienoic acid
c24u3c12c15c18 =
    .common_name = Tetracosatrienylic acid
    .systematic_name = c-12,15,18-Tetracosatrienoic acid
c24u4c9c12c15c18 =
    .common_name = Tetracosatetraenylic acid
    .systematic_name = c-9,12,15,18-Tetracosatetraenoic acid
c24u5c6c9c12c15c18 =
    .common_name = Tetracosapentaenylic acid
    .systematic_name = c-6,9,12,15,18-Tetracosapentaenoic acid
c24u6c6c9c12c15c18c21 =
    .common_name = Tetracosahexaenylic acid
    .systematic_name = c-6,9,12,15,18,21-Tetracosahexaenoic acid
c25u0 =
    .common_name = Hyenic acid
    .systematic_name = Pentacosanoic acid
c26u0 =
    .abbreviation = Ce
    .common_name = Cerotic acid
    .systematic_name = Hexacosanoic acid
c26u1c17 =
    .abbreviation = Xi
    .common_name = Ximenic acid
    .systematic_name = c-17-Hexacosenoic acid
c26u2x =
    .common_name = Hexacosadienylic acid
    .systematic_name = Hexacosadienoic acid
c26u3x =
    .common_name = Hexacosatrienylic acid
    .systematic_name = Hexacosatrienoic acid
c26u4x =
    .common_name = Hexacosatetraenylic acid
    .systematic_name = Hexacosatetraenoic acid
c26u5x =
    .common_name = Hexacosapentaenylic acid
    .systematic_name = Hexacosapentaenoic acid
c26u6x =
    .common_name = Hexacosahexaenylic acid
    .systematic_name = Hexacosahexaenoic acid
c27u0 =
    .common_name = Carboceric acid
    .systematic_name = Heptacosanoic acid
c28u0 =
    .abbreviation = Mo
    .common_name = Montanic acid
    .systematic_name = Octacosanoic acid
c28u1x =
    .common_name = Octacosenylic acid
    .systematic_name = Octacosenoic acid
c28u2x =
    .systematic_name = Octacosadienoic acid
c29u0 =
    .common_name = Nonacosylic acid
    .systematic_name = Nonacosanoic acid
c30u0 =
    .common_name = Melissic acid
    .systematic_name = Triacontanoic acid
c30u1c21 =
    .common_name = Lumequeic acid
    .systematic_name = c-21-Triacontenoic acid
c31u0 =
    .common_name = Henatriacontylic acid
    .systematic_name = Henatriacontanoic acid
c32u0 =
    .common_name = Lacceroic acid
    .systematic_name = Dotriacontanoic acid
c32u1x =
    .common_name = Dotriacontenylic acid
    .systematic_name = Dotriacontenoic acid
c32u2x =
    .systematic_name = Dotriacontadienoic acid
c33u0 =
    .common_name = Psyllic acid
    .systematic_name = Triatriacontanoic acid
c34u0 =
    .common_name = Gheddic acid
    .systematic_name = Tetratriacontanoic acid
c34u1x =
    .common_name = Tetratriacontenylic acid
    .systematic_name = Tetratriacontenoic acid
c34u2x =
    .systematic_name = Tetratriacontadienoic acid
c35u0 =
    .common_name = Ceroplastic acid
    .systematic_name = Pentatriacontanoic acid
c36u0 =
    .common_name = Hexatriacontylic acid
    .systematic_name = Hexatriacontanoic acid
c36u1x =
    .common_name = Hexatriacontenylic acid
    .systematic_name = Hexatriacontenoic acid
c36u2x =
    .systematic_name = Hexatriacontadienoic acid