experimental = Experimental
factors = Factors 
identifier = Identifier
    .abbreviation = ID
index = Index
label = Label
theoretical = Theoretical

fatty_acid = Fatty acid
    .abbreviation = FA
triacylglycerol = Triacylglycerol
    .abbreviation = TAG
diacylglycerol = Diacylglycerol
    .abbreviation = DAG
monoacylglycerol = Monoacylglycerol
    .abbreviation = MAG
enrichment_factor = Enrichment factor
    .abbreviation = EF
selectivity_factor = Selectivity factor
    .abbreviation = SF