about = About
calculation = Calculation
composition = Composition
configuration = Configuration
create = Create
edit = Edit
grid = Grid
horizontal = Horizontal
language = Language
left_panel = Left panel
list = List
load = Load
reset_application = Reset application
reset_gui = Reset GUI
reset_table = Reset table state
resize_table = Resize table columns
save = Save
settings = Settings
tabs = Tabs
vertical = Vertical